version: "3"
services:
  # reverse-proxy:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./certs/server-cert.pem:/certs/server-cert.pem
  #     - ./certs/server-key.pem:/certs/server-key.pem
  #   ports:
  #     - 8000:80
  #   restart: always
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: sf_grpc
  # mongo-express:
  #   image: mongo-express
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
