version: "3"
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/server-cert.crt:/etc/ssl/certs/server-cert.crt
      - ./certs/server_private.pem:/etc/ssl/private/server-private.pem
    ports:
      - 8000:80
    restart: always
